alpha_blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles

  root 'main_pages#home'

  get 'home', to: 'main_pages#home'

  get 'about', to: 'main_pages#about'

end

alpha_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alpha_blog/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
end

alpha_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

alpha_blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]  
 
  def index
    @article_list = Article.all
  end

  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was succesfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
    #render plain: params[:article].inspect
    #@article = Article.new(article_params)
    #@article.save
    #redirect_to articles_path@article)
  end
  
  def edit
    #@article = Article.find(params[:id])
  end

  def update
    #@article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was succesfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    #@article = Article.find(params[:id]) 
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article was succesfully destroyed"
    redirect_to articles_path
  end

  private 
    def article_params
      params.require(:article).permit(:title,:description)
    end
    def set_article
      @article = Article.find(params[:id])
    end
end

alpha_blog/app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home
  end
  
  def about
  end

end

alpha_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

alpha_blog/app/views/articles/_form.html.erb
<%= render 'main_pages/errors', model_item: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group ">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of the article", autofocus: true%>
          </div>
        </div>

        <div class="form-group ">
          <div class="control-label col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of the article" %>
          </div>
        </div>

        <div class="form-group ">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg'%>
          </div>
        </div>
    <% end %>
  </div>
</div>


<%= render 'link_list_all' %>

<%= render 'main_pages/menu' %>

alpha_blog/app/views/articles/_link_list_all.html.erb
<div class="row">

  <%= link_to "List all articles", articles_path, class: "btn btn-info col-sm-offset-3 col-sm-6" %>
</div>

alpha_blog/app/views/articles/edit.html.erb
<div class="center">
  <h1>Edit an Article</h1>
</div>

<br>

<%= render 'form' %>

alpha_blog/app/views/articles/index.html.erb
<h1 class="center">All Articles</h1>

<div class="row ">
  <div class="col-xs-8 col-xs-offset-2">
    <%= link_to "+ New article", new_article_path, class: 'btn btn-primary btn-xs ' %>
  </div>
</div>

<br>

<% @article_list.each do |article| %>
    <div class="row ">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length: 100) %>
          </div>
          <div class="article-actions">
            <%= link_to "Show", article_path(article), class: 'btn btn-success btn-xs' %>
            <%= link_to "Edit", edit_article_path(article), class: 'btn btn-primary btn-xs' %>
            <%= link_to "Destroy", article_path(article), method: :delete,
                        data: {confirm: "Are you sure? "},
                        class: 'btn btn-danger btn-xs' %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<%= render 'main_pages/menu' %>

alpha_blog/app/views/articles/new.html.erb
<div class="center">
  <h1>Create an Article</h1>
</div>

<br>

<%= render 'form' %>

alpha_blog/app/views/articles/show.html.erb
<div class="row">
  <h1 class="center">
    Title: <%= @article.title %>
  </h1>
  <br>
</div>

<div class="row">
  <div class="panel panel-info col-xs-8 col-xs-offset-2">
    <h4 class="center"><strong>Id:</strong> <%= @article.id %></h4>
  </div>
</div>

<div class="row">
  <div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center"><strong>Description:</strong></h4>
    <hr>
    <%= @article.description %>
    <div class="article-actions">
      <%= link_to "Edit", edit_article_path(@article), class: 'btn btn-primary btn-xs' %>
      <%= link_to "Destroy", article_path(@article), method: :delete,
                  data: {confirm: "Are you sure? "},
                  class: 'btn btn-danger btn-xs' %>
    </div>
  </div>
</div>
<br>

<%= render 'link_list_all' %>

alpha_blog/app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= "#{name}" %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
  </div>
</div>

alpha_blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo" href="">Brand</a> -->
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <!-- <li><a href="#">Link</a></li> -->
        <li><%= link_to "All Articles", articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

alpha_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

alpha_blog/app/views/main_pages/_errors.html.erb
<% if model_item.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(model_item.errors.count, "Error") %>
              ocurred:
            </h2>
          </div>
          <div class="panel-body">
            <ul>
              <% model_item.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
<% end %>

alpha_blog/app/views/main_pages/_menu.html.erb
<div class="container">
  <footer class="footer">
    <small> Copyright &copy; <a href="mailto:author@here.com">Author</a> 2017 </small>
    <nav>
      <ul>
       <li><%= link_to "Home", home_path %></li>
       <li><%= link_to "All Articles", articles_path %></li>
       <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

alpha_blog/app/views/main_pages/about.html.erb
<h2>Something about Alpha Blog</h2>

<p>This app/page was created in Ruby on Rails, as a part of 101 tutorial.</p>
<a href="mailto:author@example.com?subject=subject&cc=cc@example.com" target="blank">Mail to author</a>

<%= render 'main_pages/menu' %>

alpha_blog/app/views/main_pages/home.html.erb
<div class="jumbotron center">
  <h1>Alpha Blog!</h1>
  <p>Welcom welcome welcome</p>
  <p>
    <%= link_to "All Articles", articles_path, class:"btn btn-primary btn-lg" %>

    <%= link_to "Sign Up", "#", class:"btn btn-primary btn-lg" %>
  </p>
</div>
<%= render 'main_pages/menu' %>